name: Build

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup frontend env
        run: |
          cd client
          echo "VITE_APP_API_URL=${{ secrets.APP_API_URL }}" >> .env
          echo "VITE_APP_RECAPTCHA_SITE_KEY=${{ secrets.APP_RECAPTCHA_SITE_KEY }}" >> .env
          echo "VITE_APP_SESSION=${{ secrets.APP_SESSION }}" >> .env
          echo "VITE_APP_MAINTENANCE=${{ secrets.APP_MAINTENANCE }}" >> .env
          echo "VITE_APP_SENTRY_DNS=${{ secrets.APP_SENTRY_DNS }}" >> .env
          echo "VITE_APP_GOOGLE_ANALYTICS=${{ secrets.APP_GOOGLE_ANALYTICS }}" >> .env
          echo "VITE_APP_GOOGLE_MAP=${{ secrets.APP_GOOGLE_MAP }}" >> .env
      
      - name: Build frontend
        run: |
          cd client
          npm i
          npm run build

      - name: Upload frontend
        id: push_directory_frontend
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: client/build
          destination-github-username: 'freight-capstone'
          destination-repository-name: 'core1'
          user-email: mrepol742@gmail.com
          commit-message: Production
          target-branch: core1-frontend
          
      - name: Build backend
        run: |
          cp server server-build -r
          cd server
          npm i
          npm run lint
          cd ../server-build
          rm -rf eslint.config.js obfuscate.js
          cd ..
          node server/obfuscate.js

      - name: Upload backend
        id: push_directory_backend
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: server-build/
          destination-github-username: 'freight-capstone'
          destination-repository-name: 'core1'
          user-email: mrepol742@gmail.com
          commit-message: Production
          target-branch: core1-backend