name: Build

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Setup FrontEnd Env
        run: |
          cd client
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env
          echo "REACT_APP_RECAPTCHA_SITE_KEY=${{ secrets.REACT_APP_RECAPTCHA_SITE_KEY }}" >> .env
          echo "REACT_APP_SESSION=${{ secrets.REACT_APP_SESSION }}" >> .env
          echo "REACT_APP_MAINTENANCE=${{ secrets.REACT_APP_MAINTENANCE }}" >> .env
          cd ..
      
      - name: Setup BackEnd Env
        run: |
          cd server
          cp .env.example .env
          cd ..

      - name: Build FrontEnd
        run: |
          cd client
          npm i
          cp .env.example .env
          npm run build
          cd ..
          mkdir release
          mv client/build release/client
          
      - name: Build BackEnd
        run: |
          cp server server-build -r
          cd server
          npm i
          cd ../server-build
          rm -rf eslint.config.js obfuscate.js
          cd ..
          node server/obfuscate.js
          mv server-build release/server

      - name: Upload
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: release/
          destination-github-username: 'freight-capstone'
          destination-repository-name: 'core1'
          user-email: mrepol742@gmail.com
          commit-message: Production
          target-branch: build