name: Merge PR if All Workflows Pass
on:
  workflow_run:
    workflows:
      - Label PR
      - Greetings
      - Test
    types:
      - completed

jobs:
  check-status-and-merge:
    runs-on: 'ubuntu-latest'
    if: github.repository == 'freight-capstone/core1'
    steps:
      - name: Check All Workflows Status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.workflow_run.pull_requests[0]?.number;
            
            if (!prNumber) {
              console.log("No PR associated with this run.");
              return;
            }

            const requiredWorkflows = ["Workflow 1", "Workflow 2", "Workflow 3"];
            const { data: runs } = await github.rest.actions.listWorkflowRunsForRepo({
              owner,
              repo,
              status: "completed",
              per_page: 100
            });

            const prRuns = runs.workflow_runs.filter(run => 
              run.event === "pull_request" &&
              run.pull_requests.some(pr => pr.number === prNumber) &&
              requiredWorkflows.includes(run.name) &&
              run.conclusion === "success"
            );

            if (prRuns.length === requiredWorkflows.length) {
              console.log(`All required workflows have passed. Merging PR #${prNumber}.`);
              await github.rest.pulls.merge({
                owner,
                repo,
                pull_number: prNumber
              });
            } else {
              console.log("Not all workflows are completed successfully yet.");
            }
